// Asma al Husna - Les 99 Noms d'Allah
// Données partagées par toutes les pages de l'application.
// ref : référence coranique courante (sourate:verset), null si le nom provient
// principalement de la tradition prophétique.
const NOMS_ALLAH = [
    { n: 1, nom: "Allah", arabe: "اللَّهُ", attribut: "", ref: "Coran 112:1 (Sourate Al-Ikhlas)" },
    { n: 2, nom: "Ar-Rahman", arabe: "الرَّحْمَٰنُ", attribut: "Le Très Miséricordieux", ref: "Coran 55:1" },
    { n: 3, nom: "Ar-Rahim", arabe: "الرَّحِيمُ", attribut: "Le Tout Miséricordieux", ref: "Coran 2:163" },
    { n: 4, nom: "Al-Malik", arabe: "الْمَلِكُ", attribut: "Le Souverain", ref: "Coran 59:23" },
    { n: 5, nom: "Al-Quddus", arabe: "الْقُدُّوسُ", attribut: "Le Très Saint", ref: "Coran 59:23" },
    { n: 6, nom: "As-Salam", arabe: "السَّلَامُ", attribut: "La Source de Paix", ref: "Coran 59:23" },
    { n: 7, nom: "Al-Mu'min", arabe: "الْمُؤْمِنُ", attribut: "Le Donateur de Sécurité", ref: "Coran 59:23" },
    { n: 8, nom: "Al-Muhaymin", arabe: "الْمُهَيْمِنُ", attribut: "Le Gardien", ref: "Coran 59:23" },
    { n: 9, nom: "Al-'Aziz", arabe: "الْعَزِيزُ", attribut: "Le Tout-Puissant", ref: "Coran 59:23" },
    { n: 10, nom: "Al-Jabbar", arabe: "الْجَبَّارُ", attribut: "Le Restaurateur", ref: "Coran 59:23" },
    { n: 11, nom: "Al-Mutakabbir", arabe: "الْمُتَكَبِّرُ", attribut: "Le Majestueux", ref: "Coran 59:23" },
    { n: 12, nom: "Al-Khaaliq", arabe: "الْخَالِقُ", attribut: "Le Créateur", ref: "Coran 59:24" },
    { n: 13, nom: "Al-Baari'", arabe: "الْبَارِئُ", attribut: "Le Faiseur", ref: "Coran 59:24" },
    { n: 14, nom: "Al-Musawwir", arabe: "الْمُصَوِّرُ", attribut: "Le Façonneur de Formes", ref: "Coran 59:24" },
    { n: 15, nom: "Al-Ghaffaar", arabe: "الْغَفَّارُ", attribut: "Le Pardonneur", ref: "Coran 20:82" },
    { n: 16, nom: "Al-Qahhaar", arabe: "الْقَهَّارُ", attribut: "Celui qui a le Contrôle de Tout", ref: "Coran 13:16" },
    { n: 17, nom: "Al-Wahhab", arabe: "الْوَهَّابُ", attribut: "Le Donateur de Tout", ref: "Coran 3:8" },
    { n: 18, nom: "Ar-Razzaq", arabe: "الرَّزَّاقُ", attribut: "Le Pourvoyeur", ref: "Coran 51:58" },
    { n: 19, nom: "Al-Fattah", arabe: "الْفَتَّاحُ", attribut: "L'Ouvreur", ref: "Coran 34:26" },
    { n: 20, nom: "Al-'Alim", arabe: "الْعَلِيمُ", attribut: "L'Omniscient", ref: "Coran 2:158" },
    { n: 21, nom: "Al-Qaabid", arabe: "الْقَابِضُ", attribut: "Le Rétrécisseur", ref: "Coran 2:245" },
    { n: 22, nom: "Al-Baasit", arabe: "الْبَاسِطُ", attribut: "L'Étendeur", ref: "Coran 2:245" },
    { n: 23, nom: "Al-Khaafid", arabe: "الْخَافِضُ", attribut: "L'Abaisseur", ref: "Coran 56:3" },
    { n: 24, nom: "Ar-Raafi'", arabe: "الرَّافِعُ", attribut: "L'Exaltateur", ref: "Coran 58:11" },
    { n: 25, nom: "Al-Mu'izz", arabe: "الْمُعِزُّ", attribut: "Le Donateur d'Honneur", ref: "Coran 3:26" },
    { n: 26, nom: "Al-Mudhill", arabe: "الْمُذِلُّ", attribut: "Le Donateur de Déshonneur", ref: "Coran 3:26" },
    { n: 27, nom: "As-Sami'", arabe: "السَّمِيعُ", attribut: "L'Audient", ref: "Coran 2:127" },
    { n: 28, nom: "Al-Basir", arabe: "الْبَصِيرُ", attribut: "Le Voyant", ref: "Coran 4:58" },
    { n: 29, nom: "Al-Hakam", arabe: "الْحَكَمُ", attribut: "Le Juge", ref: "Coran 22:69" },
    { n: 30, nom: "Al-'Adl", arabe: "الْعَدْلُ", attribut: "Le Juste", ref: "Coran 6:115" },
    { n: 31, nom: "Al-Latif", arabe: "اللَّطِيفُ", attribut: "Le Doux", ref: "Coran 6:103" },
    { n: 32, nom: "Al-Khabir", arabe: "الْخَبِيرُ", attribut: "Le Conscient", ref: "Coran 6:18" },
    { n: 33, nom: "Al-Halim", arabe: "الْحَلِيمُ", attribut: "Le Tolérant", ref: "Coran 2:235" },
    { n: 34, nom: "Al-'Adheem", arabe: "الْعَظِيمُ", attribut: "Le Grand", ref: "Coran 2:255" },
    { n: 35, nom: "Al-Ghafoor", arabe: "الْغَفُورُ", attribut: "Le Tout Pardonneur", ref: "Coran 2:173" },
    { n: 36, nom: "Ash-Shakoor", arabe: "الشَّكُورُ", attribut: "Le Reconnaissant", ref: "Coran 35:30" },
    { n: 37, nom: "Al-'Ali", arabe: "الْعَلِيُّ", attribut: "Le Très Haut", ref: "Coran 4:34" },
    { n: 38, nom: "Al-Kabir", arabe: "الْكَبِيرُ", attribut: "Le Plus Grand", ref: "Coran 13:9" },
    { n: 39, nom: "Al-Hafidh", arabe: "الْحَفِيظُ", attribut: "Le Préservateur", ref: "Coran 11:57" },
    { n: 40, nom: "Al-Muqit", arabe: "الْمُقِيتُ", attribut: "Le Nourricier", ref: "Coran 4:85" },
    { n: 41, nom: "Al-Hasib", arabe: "الْحَسِيبُ", attribut: "Le Juge du Jugement", ref: "Coran 4:6" },
    { n: 42, nom: "Aj-Jalil", arabe: "الْجَلِيلُ", attribut: "Le Très Honorable", ref: "Coran 55:27" },
    { n: 43, nom: "Al-Karim", arabe: "الْكَرِيمُ", attribut: "Le Généreux", ref: "Coran 27:40" },
    { n: 44, nom: "Ar-Raqib", arabe: "الرَّقِيبُ", attribut: "Le Vigilant", ref: "Coran 4:1" },
    { n: 45, nom: "Al-Mujib", arabe: "الْمُجِيبُ", attribut: "Celui qui Répond", ref: "Coran 11:61" },
    { n: 46, nom: "Al-Waasi'", arabe: "الْوَاسِعُ", attribut: "L'Englobant", ref: "Coran 2:268" },
    { n: 47, nom: "Al-Hakim", arabe: "الْحَكِيمُ", attribut: "Le Sage", ref: "Coran 31:27" },
    { n: 48, nom: "Al-Waduud", arabe: "الْوَدُودُ", attribut: "Le Gentil", ref: "Coran 11:90" },
    { n: 49, nom: "Al-Majid", arabe: "الْمَجِيدُ", attribut: "Le Tout Glorieux", ref: "Coran 11:73" },
    { n: 50, nom: "Al-Ba'ith", arabe: "الْبَاعِثُ", attribut: "Le Restaurateur de Vie", ref: "Coran 22:7" },
    { n: 51, nom: "Ash-Shahid", arabe: "الشَّهِيدُ", attribut: "Le Témoin", ref: "Coran 4:166" },
    { n: 52, nom: "Al-Haqq", arabe: "الْحَقُّ", attribut: "La Vérité", ref: "Coran 22:6" },
    { n: 53, nom: "Al-Wakil", arabe: "الْوَكِيلُ", attribut: "Le Responsable", ref: "Coran 6:102" },
    { n: 54, nom: "Al-Qawi", arabe: "الْقَوِيُّ", attribut: "Le Très Fort", ref: "Coran 22:40" },
    { n: 55, nom: "Al-Matin", arabe: "الْمَتِينُ", attribut: "Le Ferme", ref: "Coran 51:58" },
    { n: 56, nom: "Al-Wali", arabe: "الْوَلِيُّ", attribut: "L'Ami Protecteur", ref: "Coran 4:45" },
    { n: 57, nom: "Al-Hamid", arabe: "الْحَمِيدُ", attribut: "Le Digne de Louanges", ref: "Coran 14:8" },
    { n: 58, nom: "Al-Muhsi", arabe: "الْمُحْصِي", attribut: "L'Évaluateur", ref: "Coran 72:28" },
    { n: 59, nom: "Al-Mubdi'", arabe: "الْمُبْدِئُ", attribut: "L'Originateur", ref: "Coran 10:34" },
    { n: 60, nom: "Al-Mu'id", arabe: "الْمُعِيدُ", attribut: "Le Restaurateur", ref: "Coran 10:34" },
    { n: 61, nom: "Al-Muhyi", arabe: "الْمُحْيِي", attribut: "Le Donneur de Vie", ref: "Coran 30:50" },
    { n: 62, nom: "Al-Mumit", arabe: "الْمُمِيتُ", attribut: "Le Donneur de Mort", ref: "Coran 3:156" },
    { n: 63, nom: "Al-Hayy", arabe: "الْحَيُّ", attribut: "L'Éternel Vivant", ref: "Coran 2:255" },
    { n: 64, nom: "Al-Qayyuum", arabe: "الْقَيُّومُ", attribut: "Le Soutien de Tout", ref: "Coran 2:255" },
    { n: 65, nom: "Al-Wajid", arabe: "الْوَاجِدُ", attribut: "Le Trouveur", ref: null },
    { n: 66, nom: "Al-Majid", arabe: "الْمَاجِدُ", attribut: "Le Noble et Illustre", ref: "Coran 85:15" },
    { n: 67, nom: "Al-Wahid", arabe: "الْوَاحِدُ", attribut: "L'Unique et Inclusif", ref: "Coran 13:16" },
    { n: 68, nom: "As-Samad", arabe: "الصَّمَدُ", attribut: "L'Éternel et Autosuffisant", ref: "Coran 112:2" },
    { n: 69, nom: "Al-Qaadir", arabe: "الْقَادِرُ", attribut: "Celui qui a l'Autorité", ref: "Coran 6:65" },
    { n: 70, nom: "Al-Muqtadir", arabe: "الْمُقْتَدِرُ", attribut: "Celui avec le Plein Pouvoir", ref: "Coran 18:45" },
    { n: 71, nom: "Al-Muqaddim", arabe: "الْمُقَدِّمُ", attribut: "Celui qui Avance", ref: null },
    { n: 72, nom: "Al-Mu'akhkhir", arabe: "الْمُؤَخِّرُ", attribut: "Le Retardateur", ref: "Coran 71:4" },
    { n: 73, nom: "Al-Awwal", arabe: "الْأَوَّلُ", attribut: "Le Premier", ref: "Coran 57:3" },
    { n: 74, nom: "Al-Akhir", arabe: "الْآخِرُ", attribut: "Le Dernier", ref: "Coran 57:3" },
    { n: 75, nom: "Adh-Dhahir", arabe: "الظَّاهِرُ", attribut: "Le Manifeste", ref: "Coran 57:3" },
    { n: 76, nom: "Al-Batin", arabe: "الْبَاطِنُ", attribut: "Le Caché et Évident", ref: "Coran 57:3" },
    { n: 77, nom: "Al-Wali", arabe: "الْوَالِي", attribut: "Le Gouverneur", ref: "Coran 13:11" },
    { n: 78, nom: "Al-Muta'ali", arabe: "الْمُتَعَالِي", attribut: "Le Très Exalté", ref: "Coran 13:9" },
    { n: 79, nom: "Al-Barr", arabe: "الْبَرُّ", attribut: "La Source de Toute Bonté", ref: "Coran 52:28" },
    { n: 80, nom: "At-Tawwab", arabe: "التَّوَّابُ", attribut: "L'Accepteur de Repentir", ref: "Coran 2:37" },
    { n: 81, nom: "Al-Muntaqim", arabe: "الْمُنْتَقِمُ", attribut: "Le Vengeur", ref: "Coran 32:22" },
    { n: 82, nom: "Al-'Afuw", arabe: "الْعَفُوُّ", attribut: "Le Pardonneur", ref: "Coran 4:43" },
    { n: 83, nom: "Ar-Ra'uf", arabe: "الرَّءُوفُ", attribut: "Le Compatissant", ref: "Coran 3:30" },
    { n: 84, nom: "Malik-ul-Mulk", arabe: "مَالِكُ الْمُلْكِ", attribut: "Le Propriétaire de toute Souveraineté", ref: "Coran 3:26" },
    { n: 85, nom: "Dhul-Jalali wal-Ikram", arabe: "ذُو الْجَلَالِ وَالْإِكْرَامِ", attribut: "Le Seigneur de Majesté et de Générosité", ref: "Coran 55:27" },
    { n: 86, nom: "Al-Muqsit", arabe: "الْمُقْسِطُ", attribut: "Le Juste", ref: "Coran 3:18" },
    { n: 87, nom: "Aj-Jami'", arabe: "الْجَامِعُ", attribut: "Le Rassembleur", ref: "Coran 3:9" },
    { n: 88, nom: "Al-Ghani", arabe: "الْغَنِيُّ", attribut: "L'Autosuffisant", ref: "Coran 2:263" },
    { n: 89, nom: "Al-Mughni", arabe: "الْمُغْنِي", attribut: "L'Enrichisseur", ref: "Coran 9:28" },
    { n: 90, nom: "Al-Mani'", arabe: "الْمَانِعُ", attribut: "Le Préventeur", ref: null },
    { n: 91, nom: "Ad-Darr", arabe: "الضَّارُّ", attribut: "Celui qui peut Affliger", ref: null },
    { n: 92, nom: "An-Nafi'", arabe: "النَّافِعُ", attribut: "Le Bienfaiteur", ref: null },
    { n: 93, nom: "An-Nur", arabe: "النُّورُ", attribut: "La Lumière", ref: "Coran 24:35" },
    { n: 94, nom: "Al-Hadi", arabe: "الْهَادِي", attribut: "Le Guide", ref: "Coran 25:31" },
    { n: 95, nom: "Al-Badi'", arabe: "الْبَدِيعُ", attribut: "L'Incomparable", ref: "Coran 2:117" },
    { n: 96, nom: "Al-Baqi", arabe: "الْبَاقِي", attribut: "L'Éternel", ref: "Coran 20:73" },
    { n: 97, nom: "Al-Warith", arabe: "الْوَارِثُ", attribut: "L'Héritier de Tout", ref: "Coran 15:23" },
    { n: 98, nom: "Ar-Rashid", arabe: "الرَّشِيدُ", attribut: "Le Guide du Droit Chemin", ref: null },
    { n: 99, nom: "As-Sabuur", arabe: "الصَّبُورُ", attribut: "Le Patient", ref: null }
];
