// Asma al Husna - Les 99 Noms d'Allah
// Données partagées par toutes les pages de l'application.
// ref : référence coranique courante (sourate:verset), null si le nom provient
// principalement de la tradition prophétique.
// attribut    : signification en français
// attribut_tr : signification en turc (Esmâ-ül Hüsnâ anlamı)
const NOMS_ALLAH = [
    { n: 1, nom: "Allah", arabe: "اللَّهُ", attribut: "", attribut_tr: "", ref: "Coran 112:1 (Sourate Al-Ikhlas)" },
    { n: 2, nom: "Ar-Rahman", arabe: "الرَّحْمَٰنُ", attribut: "Le Très Miséricordieux", attribut_tr: "Rahmeti her şeyi kuşatan, çok merhamet eden", ref: "Coran 55:1" },
    { n: 3, nom: "Ar-Rahim", arabe: "الرَّحِيمُ", attribut: "Le Tout Miséricordieux", attribut_tr: "Müminlere çok merhamet eden, bağışlayan", ref: "Coran 2:163" },
    { n: 4, nom: "Al-Malik", arabe: "الْمَلِكُ", attribut: "Le Souverain", attribut_tr: "Mülkün gerçek sahibi ve hükümdarı", ref: "Coran 59:23" },
    { n: 5, nom: "Al-Quddus", arabe: "الْقُدُّوسُ", attribut: "Le Très Saint", attribut_tr: "Her türlü eksiklikten uzak, mukaddes olan", ref: "Coran 59:23" },
    { n: 6, nom: "As-Salam", arabe: "السَّلَامُ", attribut: "La Source de Paix", attribut_tr: "Esenlik veren, selâmete çıkaran", ref: "Coran 59:23" },
    { n: 7, nom: "Al-Mu'min", arabe: "الْمُؤْمِنُ", attribut: "Le Donateur de Sécurité", attribut_tr: "Güven veren, emin kılan", ref: "Coran 59:23" },
    { n: 8, nom: "Al-Muhaymin", arabe: "الْمُهَيْمِنُ", attribut: "Le Gardien", attribut_tr: "Her şeyi gözetip koruyan", ref: "Coran 59:23" },
    { n: 9, nom: "Al-'Aziz", arabe: "الْعَزِيزُ", attribut: "Le Tout-Puissant", attribut_tr: "Mutlak güç sahibi, üstün ve yenilmez", ref: "Coran 59:23" },
    { n: 10, nom: "Al-Jabbar", arabe: "الْجَبَّارُ", attribut: "Le Restaurateur", attribut_tr: "İradesini her durumda yürüten, ıslah eden", ref: "Coran 59:23" },
    { n: 11, nom: "Al-Mutakabbir", arabe: "الْمُتَكَبِّرُ", attribut: "Le Majestueux", attribut_tr: "Büyüklükte eşi olmayan, azamet sahibi", ref: "Coran 59:23" },
    { n: 12, nom: "Al-Khaaliq", arabe: "الْخَالِقُ", attribut: "Le Créateur", attribut_tr: "Yaratan, takdir edip var eden", ref: "Coran 59:24" },
    { n: 13, nom: "Al-Baari'", arabe: "الْبَارِئُ", attribut: "Le Faiseur", attribut_tr: "Yokken kusursuzca var eden", ref: "Coran 59:24" },
    { n: 14, nom: "Al-Musawwir", arabe: "الْمُصَوِّرُ", attribut: "Le Façonneur de Formes", attribut_tr: "Her şeye şekil ve suret veren", ref: "Coran 59:24" },
    { n: 15, nom: "Al-Ghaffaar", arabe: "الْغَفَّارُ", attribut: "Le Pardonneur", attribut_tr: "Günahları çokça örten ve bağışlayan", ref: "Coran 20:82" },
    { n: 16, nom: "Al-Qahhaar", arabe: "الْقَهَّارُ", attribut: "Celui qui a le Contrôle de Tout", attribut_tr: "Her şeye gücü yeten, kahredici olan", ref: "Coran 13:16" },
    { n: 17, nom: "Al-Wahhab", arabe: "الْوَهَّابُ", attribut: "Le Donateur de Tout", attribut_tr: "Karşılıksız çokça veren, bağışlayan", ref: "Coran 3:8" },
    { n: 18, nom: "Ar-Razzaq", arabe: "الرَّزَّاقُ", attribut: "Le Pourvoyeur", attribut_tr: "Bütün canlıların rızkını veren", ref: "Coran 51:58" },
    { n: 19, nom: "Al-Fattah", arabe: "الْفَتَّاحُ", attribut: "L'Ouvreur", attribut_tr: "Hayır kapılarını açan, hükmeden", ref: "Coran 34:26" },
    { n: 20, nom: "Al-'Alim", arabe: "الْعَلِيمُ", attribut: "L'Omniscient", attribut_tr: "Her şeyi hakkıyla bilen", ref: "Coran 2:158" },
    { n: 21, nom: "Al-Qaabid", arabe: "الْقَابِضُ", attribut: "Le Rétrécisseur", attribut_tr: "Dilediğine darlık veren, ruhları kabzeden", ref: "Coran 2:245" },
    { n: 22, nom: "Al-Baasit", arabe: "الْبَاسِطُ", attribut: "L'Étendeur", attribut_tr: "Dilediğine bolluk ve genişlik veren", ref: "Coran 2:245" },
    { n: 23, nom: "Al-Khaafid", arabe: "الْخَافِضُ", attribut: "L'Abaisseur", attribut_tr: "Dilediğini alçaltan", ref: "Coran 56:3" },
    { n: 24, nom: "Ar-Raafi'", arabe: "الرَّافِعُ", attribut: "L'Exaltateur", attribut_tr: "Dilediğini yücelten, yükselten", ref: "Coran 58:11" },
    { n: 25, nom: "Al-Mu'izz", arabe: "الْمُعِزُّ", attribut: "Le Donateur d'Honneur", attribut_tr: "Dilediğine izzet ve şeref veren", ref: "Coran 3:26" },
    { n: 26, nom: "Al-Mudhill", arabe: "الْمُذِلُّ", attribut: "Le Donateur de Déshonneur", attribut_tr: "Dilediğini zillete düşüren", ref: "Coran 3:26" },
    { n: 27, nom: "As-Sami'", arabe: "السَّمِيعُ", attribut: "L'Audient", attribut_tr: "Her şeyi işiten", ref: "Coran 2:127" },
    { n: 28, nom: "Al-Basir", arabe: "الْبَصِيرُ", attribut: "Le Voyant", attribut_tr: "Her şeyi gören", ref: "Coran 4:58" },
    { n: 29, nom: "Al-Hakam", arabe: "الْحَكَمُ", attribut: "Le Juge", attribut_tr: "Mutlak hüküm veren, hakkı bâtıldan ayıran", ref: "Coran 22:69" },
    { n: 30, nom: "Al-'Adl", arabe: "الْعَدْلُ", attribut: "Le Juste", attribut_tr: "Mutlak adalet sahibi", ref: "Coran 6:115" },
    { n: 31, nom: "Al-Latif", arabe: "اللَّطِيفُ", attribut: "Le Doux", attribut_tr: "En ince işleri bilen, lütuf ve ihsan sahibi", ref: "Coran 6:103" },
    { n: 32, nom: "Al-Khabir", arabe: "الْخَبِيرُ", attribut: "Le Conscient", attribut_tr: "Her şeyin iç yüzünden haberdar olan", ref: "Coran 6:18" },
    { n: 33, nom: "Al-Halim", arabe: "الْحَلِيمُ", attribut: "Le Tolérant", attribut_tr: "Cezada acele etmeyen, yumuşak davranan", ref: "Coran 2:235" },
    { n: 34, nom: "Al-'Adheem", arabe: "الْعَظِيمُ", attribut: "Le Grand", attribut_tr: "Pek yüce, azamet sahibi", ref: "Coran 2:255" },
    { n: 35, nom: "Al-Ghafoor", arabe: "الْغَفُورُ", attribut: "Le Tout Pardonneur", attribut_tr: "Günahları çok bağışlayan", ref: "Coran 2:173" },
    { n: 36, nom: "Ash-Shakoor", arabe: "الشَّكُورُ", attribut: "Le Reconnaissant", attribut_tr: "Az iyiliğe çok karşılık veren", ref: "Coran 35:30" },
    { n: 37, nom: "Al-'Ali", arabe: "الْعَلِيُّ", attribut: "Le Très Haut", attribut_tr: "Pek yüce ve yüksek olan", ref: "Coran 4:34" },
    { n: 38, nom: "Al-Kabir", arabe: "الْكَبِيرُ", attribut: "Le Plus Grand", attribut_tr: "Büyüklükte sınırı olmayan, en büyük", ref: "Coran 13:9" },
    { n: 39, nom: "Al-Hafidh", arabe: "الْحَفِيظُ", attribut: "Le Préservateur", attribut_tr: "Her şeyi koruyan ve gözeten", ref: "Coran 11:57" },
    { n: 40, nom: "Al-Muqit", arabe: "الْمُقِيتُ", attribut: "Le Nourricier", attribut_tr: "Rızık ve kuvvet veren, koruyup besleyen", ref: "Coran 4:85" },
    { n: 41, nom: "Al-Hasib", arabe: "الْحَسِيبُ", attribut: "Le Juge du Jugement", attribut_tr: "Herkesi hesaba çeken, kullarına kâfi gelen", ref: "Coran 4:6" },
    { n: 42, nom: "Aj-Jalil", arabe: "الْجَلِيلُ", attribut: "Le Très Honorable", attribut_tr: "Celâl ve azamet sahibi", ref: "Coran 55:27" },
    { n: 43, nom: "Al-Karim", arabe: "الْكَرِيمُ", attribut: "Le Généreux", attribut_tr: "Cömert, çok ikram ve ihsan eden", ref: "Coran 27:40" },
    { n: 44, nom: "Ar-Raqib", arabe: "الرَّقِيبُ", attribut: "Le Vigilant", attribut_tr: "Her şeyi gözetleyen, kontrol eden", ref: "Coran 4:1" },
    { n: 45, nom: "Al-Mujib", arabe: "الْمُجِيبُ", attribut: "Celui qui Répond", attribut_tr: "Dualara karşılık veren", ref: "Coran 11:61" },
    { n: 46, nom: "Al-Waasi'", arabe: "الْوَاسِعُ", attribut: "L'Englobant", attribut_tr: "İlmi ve rahmeti her şeyi kuşatan", ref: "Coran 2:268" },
    { n: 47, nom: "Al-Hakim", arabe: "الْحَكِيمُ", attribut: "Le Sage", attribut_tr: "Her işi hikmetli olan", ref: "Coran 31:27" },
    { n: 48, nom: "Al-Waduud", arabe: "الْوَدُودُ", attribut: "Le Gentil", attribut_tr: "Çok seven ve çok sevilen", ref: "Coran 11:90" },
    { n: 49, nom: "Al-Majid", arabe: "الْمَجِيدُ", attribut: "Le Tout Glorieux", attribut_tr: "Şanı yüce ve şerefli olan", ref: "Coran 11:73" },
    { n: 50, nom: "Al-Ba'ith", arabe: "الْبَاعِثُ", attribut: "Le Restaurateur de Vie", attribut_tr: "Ölüleri yeniden dirilten", ref: "Coran 22:7" },
    { n: 51, nom: "Ash-Shahid", arabe: "الشَّهِيدُ", attribut: "Le Témoin", attribut_tr: "Her şeye şahit olan", ref: "Coran 4:166" },
    { n: 52, nom: "Al-Haqq", arabe: "الْحَقُّ", attribut: "La Vérité", attribut_tr: "Varlığı gerçek ve değişmez olan, hak", ref: "Coran 22:6" },
    { n: 53, nom: "Al-Wakil", arabe: "الْوَكِيلُ", attribut: "Le Responsable", attribut_tr: "Kendisine güvenilip dayanılan, işleri yöneten", ref: "Coran 6:102" },
    { n: 54, nom: "Al-Qawi", arabe: "الْقَوِيُّ", attribut: "Le Très Fort", attribut_tr: "Kudreti sonsuz, pek güçlü olan", ref: "Coran 22:40" },
    { n: 55, nom: "Al-Matin", arabe: "الْمَتِينُ", attribut: "Le Ferme", attribut_tr: "Çok sağlam, kuvveti hiç azalmayan", ref: "Coran 51:58" },
    { n: 56, nom: "Al-Wali", arabe: "الْوَلِيُّ", attribut: "L'Ami Protecteur", attribut_tr: "Müminlerin dostu, yardımcısı ve koruyucusu", ref: "Coran 4:45" },
    { n: 57, nom: "Al-Hamid", arabe: "الْحَمِيدُ", attribut: "Le Digne de Louanges", attribut_tr: "Her türlü övgüye layık olan", ref: "Coran 14:8" },
    { n: 58, nom: "Al-Muhsi", arabe: "الْمُحْصِي", attribut: "L'Évaluateur", attribut_tr: "Her şeyi tek tek sayan ve bilen", ref: "Coran 72:28" },
    { n: 59, nom: "Al-Mubdi'", arabe: "الْمُبْدِئُ", attribut: "L'Originateur", attribut_tr: "Her şeyi örneksiz, ilk olarak yaratan", ref: "Coran 10:34" },
    { n: 60, nom: "Al-Mu'id", arabe: "الْمُعِيدُ", attribut: "Le Restaurateur", attribut_tr: "Yarattıklarını öldükten sonra yeniden dirilten", ref: "Coran 10:34" },
    { n: 61, nom: "Al-Muhyi", arabe: "الْمُحْيِي", attribut: "Le Donneur de Vie", attribut_tr: "Hayat veren, can bağışlayan", ref: "Coran 30:50" },
    { n: 62, nom: "Al-Mumit", arabe: "الْمُمِيتُ", attribut: "Le Donneur de Mort", attribut_tr: "Ölümü yaratan, can alan", ref: "Coran 3:156" },
    { n: 63, nom: "Al-Hayy", arabe: "الْحَيُّ", attribut: "L'Éternel Vivant", attribut_tr: "Daima diri olan, ölümsüz", ref: "Coran 2:255" },
    { n: 64, nom: "Al-Qayyuum", arabe: "الْقَيُّومُ", attribut: "Le Soutien de Tout", attribut_tr: "Her şeyi ayakta tutan ve yöneten", ref: "Coran 2:255" },
    { n: 65, nom: "Al-Wajid", arabe: "الْوَاجِدُ", attribut: "Le Trouveur", attribut_tr: "İstediğini istediği anda bulan, hiçbir şeye muhtaç olmayan", ref: null },
    { n: 66, nom: "Al-Majid", arabe: "الْمَاجِدُ", attribut: "Le Noble et Illustre", attribut_tr: "Şanı ve keremi yüce olan", ref: "Coran 85:15" },
    { n: 67, nom: "Al-Wahid", arabe: "الْوَاحِدُ", attribut: "L'Unique et Inclusif", attribut_tr: "Zâtında, sıfatlarında ve işlerinde tek olan", ref: "Coran 13:16" },
    { n: 68, nom: "As-Samad", arabe: "الصَّمَدُ", attribut: "L'Éternel et Autosuffisant", attribut_tr: "Her şey kendisine muhtaç, kendisi hiçbir şeye muhtaç olmayan", ref: "Coran 112:2" },
    { n: 69, nom: "Al-Qaadir", arabe: "الْقَادِرُ", attribut: "Celui qui a l'Autorité", attribut_tr: "Her şeye gücü yeten", ref: "Coran 6:65" },
    { n: 70, nom: "Al-Muqtadir", arabe: "الْمُقْتَدِرُ", attribut: "Celui avec le Plein Pouvoir", attribut_tr: "Kuvvet ve kudret sahibi, dilediğini yapan", ref: "Coran 18:45" },
    { n: 71, nom: "Al-Muqaddim", arabe: "الْمُقَدِّمُ", attribut: "Celui qui Avance", attribut_tr: "Dilediğini öne alan, ileri geçiren", ref: null },
    { n: 72, nom: "Al-Mu'akhkhir", arabe: "الْمُؤَخِّرُ", attribut: "Le Retardateur", attribut_tr: "Dilediğini geri bırakan, erteleyen", ref: "Coran 71:4" },
    { n: 73, nom: "Al-Awwal", arabe: "الْأَوَّلُ", attribut: "Le Premier", attribut_tr: "Başlangıcı olmayan, her şeyden önce var olan", ref: "Coran 57:3" },
    { n: 74, nom: "Al-Akhir", arabe: "الْآخِرُ", attribut: "Le Dernier", attribut_tr: "Sonu olmayan, her şey yok olduktan sonra bâki kalan", ref: "Coran 57:3" },
    { n: 75, nom: "Adh-Dhahir", arabe: "الظَّاهِرُ", attribut: "Le Manifeste", attribut_tr: "Varlığı sayısız delille aşikâr olan", ref: "Coran 57:3" },
    { n: 76, nom: "Al-Batin", arabe: "الْبَاطِنُ", attribut: "Le Caché et Évident", attribut_tr: "Akıllarla kavranamayan, gizli olan", ref: "Coran 57:3" },
    { n: 77, nom: "Al-Wali", arabe: "الْوَالِي", attribut: "Le Gouverneur", attribut_tr: "Kâinatı yöneten ve idare eden", ref: "Coran 13:11" },
    { n: 78, nom: "Al-Muta'ali", arabe: "الْمُتَعَالِي", attribut: "Le Très Exalté", attribut_tr: "Her türlü noksanlıktan uzak, pek yüce olan", ref: "Coran 13:9" },
    { n: 79, nom: "Al-Barr", arabe: "الْبَرُّ", attribut: "La Source de Toute Bonté", attribut_tr: "İyilik ve ihsanı bol olan", ref: "Coran 52:28" },
    { n: 80, nom: "At-Tawwab", arabe: "التَّوَّابُ", attribut: "L'Accepteur de Repentir", attribut_tr: "Tövbeleri çokça kabul eden", ref: "Coran 2:37" },
    { n: 81, nom: "Al-Muntaqim", arabe: "الْمُنْتَقِمُ", attribut: "Le Vengeur", attribut_tr: "Suçluları adaletle cezalandıran", ref: "Coran 32:22" },
    { n: 82, nom: "Al-'Afuw", arabe: "الْعَفُوُّ", attribut: "Le Pardonneur", attribut_tr: "Günahları affeden, silip yok eden", ref: "Coran 4:43" },
    { n: 83, nom: "Ar-Ra'uf", arabe: "الرَّءُوفُ", attribut: "Le Compatissant", attribut_tr: "Çok şefkatli ve pek merhametli", ref: "Coran 3:30" },
    { n: 84, nom: "Malik-ul-Mulk", arabe: "مَالِكُ الْمُلْكِ", attribut: "Le Propriétaire de toute Souveraineté", attribut_tr: "Bütün mülkün gerçek sahibi", ref: "Coran 3:26" },
    { n: 85, nom: "Dhul-Jalali wal-Ikram", arabe: "ذُو الْجَلَالِ وَالْإِكْرَامِ", attribut: "Le Seigneur de Majesté et de Générosité", attribut_tr: "Celâl, azamet ve ikram sahibi", ref: "Coran 55:27" },
    { n: 86, nom: "Al-Muqsit", arabe: "الْمُقْسِطُ", attribut: "Le Juste", attribut_tr: "Bütün işlerini denk ve adaletle yapan", ref: "Coran 3:18" },
    { n: 87, nom: "Aj-Jami'", arabe: "الْجَامِعُ", attribut: "Le Rassembleur", attribut_tr: "Dilediğini dilediği zaman bir araya toplayan", ref: "Coran 3:9" },
    { n: 88, nom: "Al-Ghani", arabe: "الْغَنِيُّ", attribut: "L'Autosuffisant", attribut_tr: "Hiçbir şeye muhtaç olmayan, zengin olan", ref: "Coran 2:263" },
    { n: 89, nom: "Al-Mughni", arabe: "الْمُغْنِي", attribut: "L'Enrichisseur", attribut_tr: "Dilediğini zengin kılan, ihtiyaçtan kurtaran", ref: "Coran 9:28" },
    { n: 90, nom: "Al-Mani'", arabe: "الْمَانِعُ", attribut: "Le Préventeur", attribut_tr: "Dilemediği şeylere engel olan, koruyan", ref: null },
    { n: 91, nom: "Ad-Darr", arabe: "الضَّارُّ", attribut: "Celui qui peut Affliger", attribut_tr: "Adaletiyle elem ve zarar verebilen", ref: null },
    { n: 92, nom: "An-Nafi'", arabe: "النَّافِعُ", attribut: "Le Bienfaiteur", attribut_tr: "Fayda ve menfaat veren", ref: null },
    { n: 93, nom: "An-Nur", arabe: "النُّورُ", attribut: "La Lumière", attribut_tr: "Âlemleri aydınlatan nur, hidayet veren", ref: "Coran 24:35" },
    { n: 94, nom: "Al-Hadi", arabe: "الْهَادِي", attribut: "Le Guide", attribut_tr: "Hidayet veren, doğru yola ileten", ref: "Coran 25:31" },
    { n: 95, nom: "Al-Badi'", arabe: "الْبَدِيعُ", attribut: "L'Incomparable", attribut_tr: "Örneksiz, eşsiz ve hayranlık verici yaratan", ref: "Coran 2:117" },
    { n: 96, nom: "Al-Baqi", arabe: "الْبَاقِي", attribut: "L'Éternel", attribut_tr: "Varlığının sonu olmayan, ebedî olan", ref: "Coran 20:73" },
    { n: 97, nom: "Al-Warith", arabe: "الْوَارِثُ", attribut: "L'Héritier de Tout", attribut_tr: "Her şeyin gerçek sahibi, hepsinin vârisi", ref: "Coran 15:23" },
    { n: 98, nom: "Ar-Rashid", arabe: "الرَّشِيدُ", attribut: "Le Guide du Droit Chemin", attribut_tr: "Doğru yolu gösteren, irşad eden", ref: null },
    { n: 99, nom: "As-Sabuur", arabe: "الصَّبُورُ", attribut: "Le Patient", attribut_tr: "Çok sabırlı olan, cezada acele etmeyen", ref: null }
];
